Update bin files

diff --git a/bin/report b/bin/report
--- a/bin/report
+++ b/bin/report
@@ -3,80 +3,82 @@
 
 ### Configure environment
 
-set -o errexit    # always exit on error
-set -o pipefail   # don't ignore exit codes when piping output
+set -o errexit  # always exit on error
+set -o pipefail # don't ignore exit codes when piping output
 
-BUILD_DIR=${1:-}
-CACHE_DIR=${2:-}
-BP_DIR=$(cd "$(dirname "${0:-}")"; cd ..; pwd)
+BUILD_DIR=${1-}
+CACHE_DIR=${2-}
+BP_DIR=$(
+	cd "$(dirname "${0-}")"
+	cd ..
+	pwd
+)
 
 ### Load dependencies
 
 # shellcheck source=lib/vendor/stdlib_v7.sh
-source "$BP_DIR/lib/vendor/stdlib_v7.sh"
+source "${BP_DIR}/lib/vendor/stdlib_v7.sh"
 # shellcheck source=lib/output.sh
-source "$BP_DIR/lib/output.sh"
+source "${BP_DIR}/lib/output.sh"
 # shellcheck source=lib/monitor.sh
-source "$BP_DIR/lib/monitor.sh"
+source "${BP_DIR}/lib/monitor.sh"
 # shellcheck source=lib/environment.sh
-source "$BP_DIR/lib/environment.sh"
+source "${BP_DIR}/lib/environment.sh"
 # shellcheck source=lib/failure.sh
-source "$BP_DIR/lib/failure.sh"
+source "${BP_DIR}/lib/failure.sh"
 # shellcheck source=lib/binaries.sh
-source "$BP_DIR/lib/binaries.sh"
+source "${BP_DIR}/lib/binaries.sh"
 # shellcheck source=lib/json.sh
-source "$BP_DIR/lib/json.sh"
+source "${BP_DIR}/lib/json.sh"
 # shellcheck source=lib/cache.sh
-source "$BP_DIR/lib/cache.sh"
+source "${BP_DIR}/lib/cache.sh"
 # shellcheck source=lib/dependencies.sh
-source "$BP_DIR/lib/dependencies.sh"
+source "${BP_DIR}/lib/dependencies.sh"
 # shellcheck source=lib/plugin.sh
-source "$BP_DIR/lib/plugin.sh"
+source "${BP_DIR}/lib/plugin.sh"
 # shellcheck source=lib/uuid.sh
-source "$BP_DIR/lib/uuid.sh"
+source "${BP_DIR}/lib/uuid.sh"
 # shellcheck source=lib/kvstore.sh
-source "$BP_DIR/lib/kvstore.sh"
+source "${BP_DIR}/lib/kvstore.sh"
 # shellcheck source=lib/metadata.sh
-source "$BP_DIR/lib/metadata.sh"
-# shellcheck source=lib/features.sh
-source "$BP_DIR/lib/features.sh"
+source "${BP_DIR}/lib/metadata.sh"
 # shellcheck source=lib/builddata.sh
-source "$BP_DIR/lib/builddata.sh"
+source "${BP_DIR}/lib/builddata.sh"
 
-export PATH="$BUILD_DIR/.heroku/node/bin:$BUILD_DIR/.heroku/yarn/bin":$PATH
+export PATH="${BUILD_DIR}/.heroku/node/bin:${BUILD_DIR}/.heroku/yarn/bin:${PATH}"
 
-meta_init "$CACHE_DIR"
-features_init "nodejs" "$BUILD_DIR" "$CACHE_DIR" "$BP_DIR/features"
+meta_init "${CACHE_DIR}"
+features_init "nodejs" "${BUILD_DIR}" "${CACHE_DIR}" "${BP_DIR}/features"
 
 # a place to build up the output YAML structure
 output=$(mktemp -t bin-reportXXXXXX)
 
 # append the key / value pair to $output, but skip if the value is empty
 kv_pair() {
-  local key value
-  key="$1"
-  value="$2"
-  if [[ -n "$value" ]]; then
-    echo "$key: $value" >> $output
-  fi
+	local key value
+	key="${1}"
+	value="${2}"
+	if [[ -n ${value} ]]; then
+		echo "${key}: ${value}" >>"${output}"
+	fi
 }
 
 # use to safely quote strings
 kv_pair_string() {
-  local key value
-  key="$1"
-  value="$2"
-  if [[ -n "$value" ]]; then
-    value=$(echo $value | sed 's/"/\\"/g')
-    echo "$key: \"$value\"" >> $output
-  fi
+	local key value
+	key="${1}"
+	value="${2}"
+	if [[ -n ${value} ]]; then
+		value=${value//\"/\\\"}
+		echo "${key}: \"${value}\"" >>"${output}"
+	fi
 }
 
 has_binary_installed() {
-  [[ -x "$(command -v "$1")" ]]
+	[[ -x "$(command -v "${1}")" ]]
 }
 
-kv_pair_string "stack" "$STACK"
+kv_pair_string "stack" "${STACK}"
 
 # the version of installed binaries
 has_binary_installed "node" && kv_pair_string "node_version" "$(node --version)"
@@ -86,18 +88,18 @@ has_binary_installed "pnpm" && kv_pair_string "pnpm_version" "$(pnpm --version)"
 has_binary_installed "corepack" && kv_pair_string "corepack_version" "$(corepack --version)"
 
 # what versions were requested
-kv_pair_string "node_version_request" "$(read_json "$BUILD_DIR/package.json" ".engines.node")"
-kv_pair_string "npm_version_request" "$(read_json "$BUILD_DIR/package.json" ".engines.npm")"
-kv_pair_string "yarn_version_request" "$(read_json "$BUILD_DIR/package.json" ".engines.yarn")"
-kv_pair_string "pnpm_version_request" "$(read_json "$BUILD_DIR/package.json" ".engines.pnpm")"
-kv_pair_string "package_manager_request" "$(read_json "$BUILD_DIR/package.json" ".packageManager")"
+kv_pair_string "node_version_request" "$(read_json "${BUILD_DIR}/package.json" ".engines.node")"
+kv_pair_string "npm_version_request" "$(read_json "${BUILD_DIR}/package.json" ".engines.npm")"
+kv_pair_string "yarn_version_request" "$(read_json "${BUILD_DIR}/package.json" ".engines.yarn")"
+kv_pair_string "pnpm_version_request" "$(read_json "${BUILD_DIR}/package.json" ".engines.pnpm")"
+kv_pair_string "package_manager_request" "$(read_json "${BUILD_DIR}/package.json" ".packageManager")"
 
 # build scripts
-kv_pair_string "start_script" "$(read_json "$BUILD_DIR/package.json" ".scripts[\"start\"]")"
-kv_pair_string "build_script" "$(read_json "$BUILD_DIR/package.json" ".scripts[\"build\"]")"
-kv_pair_string "postinstall_script" "$(read_json "$BUILD_DIR/package.json" ".scripts[\"postinstall\"]")"
-kv_pair_string "heroku_prebuild_script" "$(read_json "$BUILD_DIR/package.json" ".scripts[\"heroku-prebuild\"]")"
-kv_pair_string "heroku_postbuild_script" "$(read_json "$BUILD_DIR/package.json" ".scripts[\"heroku-postbuild\"]")"
+kv_pair_string "start_script" "$(read_json "${BUILD_DIR}/package.json" '.scripts["start"]')"
+kv_pair_string "build_script" "$(read_json "${BUILD_DIR}/package.json" '.scripts["build"]')"
+kv_pair_string "postinstall_script" "$(read_json "${BUILD_DIR}/package.json" '.scripts["postinstall"]')"
+kv_pair_string "heroku_prebuild_script" "$(read_json "${BUILD_DIR}/package.json" '.scripts["heroku-prebuild"]')"
+kv_pair_string "heroku_postbuild_script" "$(read_json "${BUILD_DIR}/package.json" '.scripts["heroku-postbuild"]')"
 kv_pair "build_script_time" "$(meta_get "build-script-time")"
 kv_pair "build_script_memory" "$(meta_get "build-script-memory")"
 kv_pair "postinstall_script_time" "$(meta_get "postinstall-script-time")"
@@ -114,11 +116,11 @@ kv_pair_string "package_manager" "$(meta_get "node-package-manager")"
 kv_pair "lock_file" "$(meta_get "has-node-lock-file")"
 
 # does this project use "workspaces"?
-kv_pair "uses_workspaces" "$(json_has_key "$BUILD_DIR/package.json" "workspaces")"
+kv_pair "uses_workspaces" "$(json_has_key "${BUILD_DIR}/package.json" "workspaces")"
 # what workspaces are defined? Logs as: `["packages/*","a","b"]`
-kv_pair_string "workspaces" "$(read_json "$BUILD_DIR/package.json" ".workspaces")"
+kv_pair_string "workspaces" "$(read_json "${BUILD_DIR}/package.json" ".workspaces")"
 # count # of js, cjs, mjs, jsx, ts, coffee, vue, and html files to approximate project size, exclude any files in node_modules
-kv_pair "num_project_files" "$(find "$BUILD_DIR" -name '*.js' -o -name '*.cjs' -o -name '*.mjs' -o  -name '*.ts' -o -name '*.jsx' -o -name '*.coffee' -o -name '*.vue' -o -name '*.html' | grep -cv node_modules | tr -d '[:space:]')"
+kv_pair "num_project_files" "$(find "${BUILD_DIR}" -name '*.js' -o -name '*.cjs' -o -name '*.mjs' -o -name '*.ts' -o -name '*.jsx' -o -name '*.coffee' -o -name '*.vue' -o -name '*.html' | grep -cv node_modules | tr -d '[:space:]')"
 # measure how large node_modules is on disk
 kv_pair "node_modules_size" "$(measure_size)"
 
@@ -161,10 +163,10 @@ kv_pair_string "resolve_v2_error" "$(meta_get "resolve-v2-error")"
 
 # save which features were turned on or off
 features_list | tr ' ' '\n' | while read -r key; do
-  if [[ -n $key ]]; then
-    kv_pair "feature-$key" "$(features_get "$key")"
-  fi
+	if [[ -n ${key} ]]; then
+		kv_pair "feature-${key}" "$(features_get "${key}")"
+	fi
 done
 
 # emit the metadata on stdout
-cat $output
+cat "${output}"
